apiVersion: v1
kind: Service
metadata:
  name: ivia-runtime-db
spec:
  ports:
    - port: 5432
      name: postgresql
      protocol: TCP
      targetPort: postgresql
  selector:
    app: ivia-runtime-db
  type: ClusterIP
