apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
    - port: 8080
      name: demo-app
      protocol: TCP
      targetPort: 8080
  selector:
    app: demo-app
  type: ClusterIP
