apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-ldapslapd
  labels:
    app: openldap
spec:
  storageClassName: ocs-external-storagecluster-cephfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
