kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'phpldapadmin-anyuid'
  labels:
    app: phpldapadmin  
subjects:
  - kind: ServiceAccount
    name: phpldapadmin
    namespace: ibm-verify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
