apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-account-key
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
    - http01:
        ingress:
          class: openshift-default