kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ivia-anyuid
subjects:
  - kind: ServiceAccount
    name: ivia-anyuid
    namespace: ibm-verify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
  #name: 'system:openshift:scc:privileged'
