kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: isvd-secret-reader-binding
subjects:
  - kind: ServiceAccount
    name: isvd
    namespace: ibm-verify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: isvd-secret-reader
