kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ivia-automated-config-job
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments
