kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-verify-argo-rb
  namespace: ibm-verify
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    #name: openshift-gitops-otp-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-verify-argo-role
