apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: openshift-gitops
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "500"
spec:
  destination:
    namespace: ibm-verify
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./env/odf/postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
