apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: mapping-rules
    files:
      - rule1.js
      - rule2.js

generatorOptions:
  disableNameSuffixHash: true