# Config for local/embedded ldap using IBM Directory Server as federated LDAP
container:
  k8s_deployments:
    namespace: "ibm-verify"
    runtime: 
      - "ivia-runtime"
    webseal:
      - "via-wrpi"
  admin_cfg:
    session_timeout: 720
  account_management:
    users:
    - name: "cfgsvc"
      operation: "update"
      password: !secret ibm-verify/ivia-secrets:cfgsvc-passwd
  management_authorization:
    authorization_enforcement: True
    roles:
    - operation: "update"
      name: "Configuration Service"
      users:
      - name: "cfgsvc"
        type: "local"
      features:
      - name: "shared_volume"
        access: "w"
  ssl_certificates:
    - name: "lmi_trust_store"
      signer_certificates:
      - "/tmp/pki/postgresql.pem"
      #- "/tmp/pki/openldap.pem"
    - name: "rt_profile_keys"
      signer_certificates:
      - "/tmp/pki/postgresql.pem"
    - name: isvd
      load_certificates:
        - port: 9636
          server: isvd-proxy
          label: isvd
    #- name: "isvd"
    #  signer_certificates:
    #  - "/tmp/pki/server_cert/server_cert" 
  cluster:
    runtime_database:
      host: "ivia-runtime-db.ibm-verify.svc.cluster.local"
      port: 5432
      type: "postgresql"
      user: "ivia"
      password: !secret ibm-verify/ivia-secrets:postgres-passwd
      ssl: False
      db_name: "ivia"
  activation: #Activation codes
    webseal: !secret ibm-verify/ivia-secrets:base-code
    access_control: !secret ibm-verify/ivia-secrets:aac-code
    federation: !secret ibm-verify/ivia-secrets:fed-code
